FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 libglx-mesa0 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml poetry.lock ./

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --only main

COPY divevision/ ./divevision/

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "divevision.src.app.main:app", "--host", "0.0.0.0", "--port", "8000"]